### ISSUE TITLE
Using Nylas Ruby v3 SDK, create a code sample to create calendar event

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#29]
Using Nylas Ruby v3 SDK, create a code sample to create calendar event

**Comment by sharsha315** [comment]
Hi @relaxedtomato, can I have the opportunity to work on this issue.

**Comment by relaxedtomato** [comment]
Sounds good @sharsha315, just assigned!

**Comment by sharsha315** [comment]
Hi @relaxedtomato, I have submitted the PR, kindly review the submission and provide feedback. Thank You.

**Comment by atejada** [comment]
Closed by PR #98

**Comment by sharsha315** [comment]
Thank you @relaxedtomato and @atejada for giving me the opportunity to contribute to Nylas. Once again thanks for your guidance and support. Also, this is my first participation in Hacktoberfest event, I am glad that I was able to make 3 PR submissions successfully for Nylas Hacktoberfest 2023 itself. This was a great learning experience for me, as I learnt Ruby programming language and made 2 contributions for nylas-hactoberfest-2023 repository. I hope to continue to learn and make more open-source contributions in future.
