### ISSUE TITLE
Using Nylas Node v3 SDK, create a code sample to create calendar

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#3]
Using Nylas Node v3 SDK, create a code sample to create calendar

**Comment by kelbri10** [comment]
Hello! I would like to take this on if possible :)

**Comment by relaxedtomato** [comment]
Thanks, @kelbri10 - just assigned this to you. Some further details:

1. Here are the details to install the Nylas SDK for Nylas v3: https://www.npmjs.com/package/nylas/v/7.0.0-beta.2
2. Send us an email at `devrel` @ `nylas.com` and we can help set up a dev account for testing the code sample.

**Comment by relaxedtomato** [comment]
thanks for the email, next steps:

1. @kelbri10 accept verification email from Nylas
2. @relaxedtomato to set up the dev dashboard for testing
3. @relaxedtomato to provide access to the dev dashboard

**Comment by kelbri10** [comment]
Accepted the email ! @relaxedtomato

**Comment by relaxedtomato** [comment]
Steps 1, 2, and 3 are done :)
