### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to read calendar

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#39]
Using Nylas Python v3 SDK, create a code sample to read calendar

**Comment by wiseaidev** [comment]
Sup! I'm ready to tackle Python-related issues. But here's the deal: do you prefer samples that are tied to a specific framework, or are you good with a straightforward Python script? I'm asking because the official example is built with Flask.

**Comment by relaxedtomato** [comment]
@wiseaidev - Python scripts are solid 👍 

Assigned ! Connect if you have questions. We will get you setup with our new dashboard for testing purposes.

Send your email over to `devrel` at `nylas.com` with the subject: `hacktoberfest23`, and we'll quickly send account details 👍

**Comment by relaxedtomato** [comment]
@wiseaidev - just following up on this ticket, are you blocked by the issues you raised on the SDK?

These are the [open issues](https://github.com/nylas/nylas-python/issues/created_by/wiseaidev) I see that you raised.

**Comment by wiseaidev** [comment]
Sup @relaxedtomato, I am currently busy doing other things. Besides, I am going to knock off all Python-related issues we have here during this weekend, starting today/tomorrow. Have a nice day, ma fren!

**Comment by relaxedtomato** [comment]
@wiseaidev, just realized we just got your email, so haven't completed this task:

Send your email over to devrel at nylas.com with the subject: hacktoberfest23, and we'll quickly send account details 👍

Will have @atejada follow up with you with an account setup so you can test your code sample #84

**Comment by wiseaidev** [comment]
Done!

**Comment by wiseaidev** [comment]
Done!

**Comment by atejada** [comment]
Resolved by PR #89
