### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to create calendar

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#40]
Using Nylas Python v3 SDK, create a code sample to create calendar

**Comment by JuanitaCathy** [comment]
I'd like to work on this issue, can u assign it to me?

**Comment by relaxedtomato** [comment]
Sure, assigned @JuanitaCathy. Some more details to help you get started:

1. Here are the details to install the Python SDK for Nylas v3: https://github.com/nylas/nylas-python/tree/v6.0.0-beta
2. Send us an email at `devrel` @ `nylas.com` and we can help set up an account for testing the code sample

**Comment by relaxedtomato** [comment]
thanks for the email, next steps:

1. @JuanitaCathy to accept verification email from Nylas
2. @relaxedtomato to set up the dev dashboard for testing
3. @relaxedtomato to provide access to the v3 dev dashboard

**Comment by relaxedtomato** [comment]
@JuanitaCathy - do you have any questions or need help completing the PR?

**Comment by JuanitaCathy** [comment]
Yes, I'm not sure how to proceed after generating the access token ie, the last step

**Comment by relaxedtomato** [comment]
@JuanitaCathy - have you taken a look at our FAQs?

Specifically connecting an account: https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/faqs.md#q-how-can-i-connect-a-user-account

**Comment by JuanitaCathy** [comment]
Yea, im facing an issue after that step, ie, add test grant

**Comment by relaxedtomato** [comment]
@JuanitaCathy  - I like to help close this ticket, would you be interested in hopping on a code share to go over the code and progress the PR?

**Comment by JuanitaCathy** [comment]
Yes okayy

**Comment by JuanitaCathy** [comment]
> @JuanitaCathy - I like to help close this ticket, would you be interested in hopping on a code share to go over the code and progress the PR?

@relaxedtomato Can you let me know when you're available to do a code check so as to progress the PR?

**Comment by relaxedtomato** [comment]
@JuanitaCathy - messaging shortly, thanks for the reminder :)

**Comment by relaxedtomato** [comment]
@JuanitaCathy - I reached out, however, did not hear back. Would you still like to work on completing this PR?

**Comment by JuanitaCathy** [comment]
> @JuanitaCathy - I reached out, however, did not hear back. Would you still like to work on completing this PR?

Hey @relaxedtomato ,  Thank you for being patient all this while, I had fun contributing to this. Unfortunately, I have exams going on now and i wont be able to work on this, I would like to unassign myself. Again, i apologize for any inconvenience caused.

**Comment by relaxedtomato** [comment]
@JuanitaCathy - totally understand, best of luck with exams.

Let me know if you like to wrap this up in a few weeks, happy to jump on a call to wrap up this PR.

**Comment by Onwuagba** [comment]
@relaxedtomato Is this now opened so I can work on it?

**Comment by relaxedtomato** [comment]
@Onwuagba - actually, it looks like its been addressed by #90 

Let me close the ticket.
