### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to get calendar availability

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#43]
Using Nylas Python v3 SDK, create a code sample to get calendar availability

**Comment by wiseaidev** [comment]
It seems like there is a bug in this method when attempting to call `client.calendars.get_availability(identifier=os.environ.get("GRANT_ID"), request_body=query_params)`, I am getting:

```sh
Error while fetching calendar events: Unrecognized request URL (POST: /v3/grants/grant-id/calendar/availability). Please see https://developer.nylas.com/docs/api/v3-beta/ or we can help at https://support.nylas.com/.
```

Probably the endpoint is not available yet. PR will be submitted soon

**Comment by atejada** [comment]
@wiseaidev Thanks, there's indeed a bug when calling get_availability method. I have already raised a PR to fix it. Your PR #91 doesn't solve it though...

**Comment by wiseaidev** [comment]
> Your PR https://github.com/nylas-samples/nylas-hacktoberfest-2023/pull/91 doesn't solve it though...
I am just demoing this method, not fixing it, know what I am sayin'? Besides, the error seems to be in the corresponding endpoint in the `nylas` sdk for the `get_availability` method when making the request. I think it should be `/v3-beta/grants/...` instead of ``/v3/grants/...`, not sure.

**Comment by atejada** [comment]
Sorry, poor choice of words from my side. Anyways, this should be fixed when my PR gets merged. I will go ahead and merge your PR (later today) as it will work eventually.
