### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to create calendar event

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#44]
Using Nylas Python v3 SDK, create a code sample to create calendar event

**Comment by sharsha315** [comment]
Hi @relaxedtomato, can I have the opportunity to work on this issue.

**Comment by atejada** [comment]
Close with PR #87

**Comment by atejada** [comment]
@wiseaidev This was already requested by @sharsha315 

It was my fault for not checking before merging, so next time, request an issue before submitting a PR, otherwise it will not be considered.

Sorry about this @sharsha315 😣

**Comment by relaxedtomato** [comment]
That's fine @wiseaidev - we are going based on open issues since it will keep our PRs more organized, we may have two people create the same PR which is additional work that cannot be merged, and not ideal.
