### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to read calendar events

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#45]
Using Nylas Python v3 SDK, create a code sample to read calendar events

**Comment by aakzsh** [comment]
Hey there @relaxedtomato,
I would like to take up this issue! Please assign it to me if that's alright.
Thanks

**Comment by relaxedtomato** [comment]
Thanks @aakzsh!

**Comment by aakzsh** [comment]
Hi @relaxedtomato, could you please check pr #80 that I've created, thanks!

**Comment by relaxedtomato** [comment]
@aakzsh - going to have @atejada take a look soon!
