### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to delete calendar event

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#46]
Using Nylas Python v3 SDK, create a code sample to delete calendar event

**Comment by aakzsh** [comment]
Hi @relaxedtomato,
I recently implemented this functionality in my project [Planorama](https://devpost.com/software/planorama) for Nylas hackathon. Could you please assign this issue to me?

Also one doubt, how should I implement it?
1. Should I make a python script that'll show the users their calendar event with respective ids, and then take the input of calendar id to delete that?
2. Should I create a flask application which would have a web interface for showing the same features?

Thanks!

**Comment by relaxedtomato** [comment]
Hi @aakzsh - thanks for the inquiry. Doing the `1. python script` is sufficient. You will need to use the Python v3 SDK, are you currently using this?

Will assign the ticket now, pass on your email to `devrel` @ `nylas.com` and we can quickly set-up a v3 dashboard account for you.

**Comment by aakzsh** [comment]
Oh I see, sure I'll use v3 SDK, wasn't using it until now. And yes, I'll drop you an email! Thanks

**Comment by relaxedtomato** [comment]
Thanks for the email, next steps:

1. @aakzsh accept verification email from Nylas
2. @relaxedtomato to set up dev dashboard for testing
3. @relaxedtomato to provide access to dev dashboard for creating credentials

**Comment by relaxedtomato** [comment]
@aakzsh, steps 1, 2, and 3 from prev. comment are complete and you should have received a message to access the dev dashboard.

Let us know if any comes up as you prepare the code sample :)

**Comment by aakzsh** [comment]
hey @relaxedtomato, could you please check pr #77

**Comment by relaxedtomato** [comment]
Resolved by PR #77
