### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to update calendar event

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#47]
Using Nylas Python v3 SDK, create a code sample to update calendar event

**Comment by sharsha315** [comment]
Hi @relaxedtomato, if this issue is still open, I would like to work on this issue.

**Comment by relaxedtomato** [comment]
Hi @sharsha315  - looks like its been taken on by @wiseaidev, is there another ticket you like to take on?

Hi @wiseaidev - I see the PR, make sure you ask to take on the ticket first so its clear to others which tickets are available 👍
