### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to create a user grant

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#48]
Using Nylas Python v3 SDK, create a code sample to create a user grant

**Comment by gagandeepp** [comment]
Interested please assign

**Comment by relaxedtomato** [comment]
@gagandeepp assigned! 🙌

**Comment by relaxedtomato** [comment]
@gagandeepp to quickly test out the code, we can create an account for you!

Send your email over to `devrel` at `nylas.com` with the subject: `hacktoberfest23`, and we'll follow up with account details 👍

**Comment by relaxedtomato** [comment]
@gagandeepp - did you get a chance to work on the issue? Let us know if you have any questions :)

**Comment by relaxedtomato** [comment]
@gagandeepp - going to give this issue a few more days before letting someone else take a look, let us know if you have questions.

I created an FAQ for accessing our dashboard: https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/faqs.md

**Comment by wiseaidev** [comment]
Sup! I can work on this issue.

**Comment by relaxedtomato** [comment]
@wiseaidev assigned, thanks for connecting on the issues first 🙌

**Comment by relaxedtomato** [comment]
@wiseaidev - any updates on this ticket?

**Comment by atejada** [comment]
Close by PR #100
