### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to read a user grant

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#49]
Using Nylas Python v3 SDK, create a code sample to read a user grant

**Comment by wiseaidev** [comment]
Sup! I can work on this issue.

**Comment by relaxedtomato** [comment]
Sure, let me assign. @wiseaidev

**Comment by relaxedtomato** [comment]
@wiseaidev - any updates on this ticket?

**Comment by atejada** [comment]
Closed by PR #99
