### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to delete a user grant

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#51]
Using Nylas Python v3 SDK, create a code sample to delete a user grant

**Comment by wiseaidev** [comment]
Sup! I can work on this issue.

**Comment by relaxedtomato** [comment]
Sure, let me assign. @wiseaidev

**Comment by relaxedtomato** [comment]
@wiseaidev - any updates on this ticket?

**Comment by wiseaidev** [comment]
On my checklist for Sunday. Have a nice weekend, fellas!

**Comment by atejada** [comment]
Closed by PR #102
