### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to create webhook

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#52]
Using Nylas Python v3 SDK, create a code sample to create webhook

**Comment by sharsha315** [comment]
Hey, I would like to take on this issue and contribute to the project. Could you please provide guidance on how to get started?

**Comment by relaxedtomato** [comment]
Hi @sharsha315, thanks for reaching out, issue assigned. Here are some details:

1. Here are the details to install the Python SDK for Nylas v3: https://github.com/nylas/nylas-python/tree/v6.0.0-beta
2. Send us an email at `devrel` @ `nylas.com` and we can help set up an account for testing the code sample
3. On the [readme](https://github.com/nylas-samples/nylas-hacktoberfest-2023), we have available resources to start, and you can always drop a message on this issue if something is not clear

**Comment by sharsha315** [comment]
Thank you for the details and the assignment. In the interest of learning about the Nylas platform, I have already created an account. Do I still need to contact as in the details provided in step 2?

**Comment by relaxedtomato** [comment]
@sharsha315 - yes, since the Nylas API v3 is a separate dashboard, we can create an account for you, its super quick!

**Comment by relaxedtomato** [comment]
You can definitely learn about Nylas from our current dashboard, but the version is only 2.7, this Github Issue is for v3.

**Comment by relaxedtomato** [comment]
Hi @sharsha315 - will take a look at your code sample shortly:

https://github.com/sharsha315/nylas-hacktoberfest-2023

**Comment by relaxedtomato** [comment]
Taking a look now: https://github.com/sharsha315/nylas-hacktoberfest-2023/tree/create-webhook-test/code-samples/webhook/python/create-webhook

**Comment by relaxedtomato** [comment]
also

`callback_url = "https://eodg8rgla17nx41.m.pipedream.net"`

is something that you need to setup yourself, if you want, do this

just leave it as `callback_url=ENTER_CALLBACK_URL`

**Comment by sharsha315** [comment]
Hi @relaxedtomato, I have submitted the PR. Kindly review the submission and provide the feedback on the same. Thank you.

**Comment by relaxedtomato** [comment]
Just saw a comment from @atejada - let's address that to close this ticket 👍

**Comment by sharsha315** [comment]
Sure Ram, I have made the necessary changes. Kindly review the changes and
provide feedback.
Thank you.

**Comment by sharsha315** [comment]
Thank you Ram, It could not have been completed without your support and
guidance.
