### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to read webhook

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#53]
Using Nylas Python v3 SDK, create a code sample to read webhook

**Comment by Onwuagba** [comment]
Hi @relaxedtomato,

Is this (or any other sample Python code) task still available? Happy to work on this.

P.S.: Coming from the just-concluded hackathon, I also wish to confirm if my test account is still valid for this, if available.

**Comment by atejada** [comment]
PR closed by #97
