### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to update webhook

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#54]
Using Nylas Python v3 SDK, create a code sample to update webhook

**Comment by Onwuagba** [comment]
Hello @relaxedtomato,


Has this being assigned? Happy to work on this.

**Comment by relaxedtomato** [comment]
@Onwuagba - Same message as other ticket, did you get setup with a v3 account? Happy to help with that so you can test the code sample.

Assigning the ticket now 🙌

**Comment by Onwuagba** [comment]
Hello @relaxedtomato. Thank you for the ticket.

I'm not certain that I'm on v3. Is there a way to confirm this, though?

**Comment by relaxedtomato** [comment]
@Onwuagba will assign the ticket now, Send your email over to `devrel` at `nylas.com` with the subject: `hacktoberfest23`, and we'll quickly send account details 👍 

cc: @atejada - can you help create the account and share next steps?

**Comment by Onwuagba** [comment]
Request sent. Thank you

**Comment by atejada** [comment]
Closed by PR #103
