### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to send event RSVP/response

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#56]
Using Nylas Python v3 SDK, create a code sample to send event RSVP/response

**Comment by navascogt** [comment]
Hi @relaxedtomato, I want to work on this issue, I will research more about the concepts of Nylas to have a better understanding in order to contribute with you.

**Comment by relaxedtomato** [comment]
@navascogt sounds good - reach out if you have questions. We can get you setup with a dashboard account for testing purposes.

Will assign the ticket now, Send your email over to `devrel` at `nylas.com` with the subject: `hacktoberfest23`, and we'll quickly send account details 👍

**Comment by relaxedtomato** [comment]
@navascogt - the readme has links to our docs and related to get your started 👍

**Comment by navascogt** [comment]
Hi @relaxedtomato, I will be uploading a Draft PR in order you to review how I solved the issue and be waiting for your comments about it.

**Comment by relaxedtomato** [comment]
@navascogt - sounds good, I assigned the PR to @atejada to take a look 👍
