### ISSUE TITLE
Using Nylas Kotlin v3 SDK, create a code sample to create calendar event

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#62]
Using Nylas Kotlin v3 SDK, create a code sample to create calendar event

**Comment by NikhilTaneja98** [comment]
Hi @relaxedtomato,
I want to work on this issue. Can you assign it to me?
Thanks

**Comment by relaxedtomato** [comment]
@NikhilTaneja98 - assigned, do check the other ticket #63 so we can setup your account to use our latest v3 dashboard.

**Comment by NikhilTaneja98** [comment]
@relaxedtomato PR submitted

**Comment by atejada** [comment]
Closed by PR #104
