### ISSUE TITLE
Using Nylas Kotlin v3 SDK, create a code sample to read calendar events

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#63]
Using Nylas Kotlin v3 SDK, create a code sample to read calendar events

**Comment by NikhilTaneja98** [comment]
Hi @relaxedtomato,
I want to work on this issue. Can you assign it to me?
Thanks

**Comment by relaxedtomato** [comment]
@NikhilTaneja98 - will assign, we just need to set you up with an account on our v3 dashboard for testing the code sample. Will be quick.

Send your email over to `devrel` at `nylas.com` with the subject: `hacktoberfest23`, and we'll quickly send account details 👍

**Comment by NikhilTaneja98** [comment]
I need to submit a support ticket on - https://support.nylas.com/hc/en-us/requests/new?

**Comment by relaxedtomato** [comment]
@NikhilTaneja98 - ah no, just send an email to `devrel` @ `nylas.com` and we will set up an account on our new dashboard for you to test out the code sample.

No need to create a support ticket :)

**Comment by relaxedtomato** [comment]
@NikhilTaneja98 - just sharing more information, our current nylas.com uses v2 of our API, we are creating code samples for hacktoberfest using the v3 of our API, so need to create an account for everyone. It’s pretty quick to get setup.

**Comment by NikhilTaneja98** [comment]
@relaxedtomato - I am using Java SDK v2 and do i need to provide only the read calendar class file or any other file as well like pom.xml(maven)?

**Comment by relaxedtomato** [comment]
@NikhilTaneja98 - perfect, Java SDK v2: https://github.com/nylas/nylas-java/tree/v2.0.0-beta

Is the correct version, did you send us an email for account creation?

**Comment by NikhilTaneja98** [comment]
Yes I did send email to devrel and i am using the same version of Java SDK.

**Comment by relaxedtomato** [comment]
@NikhilTaneja98 sounds good - I will check for your email soon and help you get setup!

**Comment by NikhilTaneja98** [comment]
@relaxedtomato PR submitted

**Comment by atejada** [comment]
Closed by PR #105
