### ISSUE TITLE
Using Nylas Kotlin v3 SDK, create a code sample to delete calendar event

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#64]
Using Nylas Kotlin v3 SDK, create a code sample to delete calendar event

**Comment by NikhilTaneja98** [comment]
Hi @relaxedtomato,
I want to contribute in this issue. Can you assign it to me?

**Comment by relaxedtomato** [comment]
@NikhilTaneja98 just assigned! 🎉

**Comment by NikhilTaneja98** [comment]
@relaxedtomato PR submitted

**Comment by atejada** [comment]
Closed PR by #106
