### ISSUE TITLE
Using Nylas Node v3 SDK, create a code sample to create a user grant

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#7]
Using Nylas Node v3 SDK, create a code sample to create a user grant

**Comment by amit-ksh** [comment]
Hey @relaxedtomato, I would like to work on this one.

**Comment by relaxedtomato** [comment]
@amit-ksh awesome - connect if you have questions. We can get you setup with our new dashboard for testing purposes.

Send your email over to `devrel` at `nylas.com` with the subject: `hacktoberfest23`, and we'll quickly send account details 👍

**Comment by amit-ksh** [comment]
@relaxedtomato, I'm having some trouble creating grants using the `nylas.auth.grants.create` method but it requires a `refreshToken`. So, I attempted to obtain a `refreshToken` using the `nylas.auth.exchangeCodeForToken`, but unfortunately, it resulted in an error. Could you please assist me with this issue?

My Code-
```js
const { code } = req.query;
const resp = await nylas.auth.exchangeCodeForToken({
  code,
});
```

Error I got when `exchangeCodeForToken` is called-

```bash
/nylas-hacktoberfest-2023/code-samples/grant/node/create/node_modules/nylas/lib/esm/apiClient.js:98
error = new NylasOAuthError(camelCaseError, response.status);
                            ^

NylasOAuthError: Internal error, contact administrator
    at APIClient.request (file:///D:/personal/open-source/nylas-hacktoberfest-2023/code-samples/grant/node/create/node_modules/nylas/lib/esm/apiClient.js:98:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///D:/personal/open-source/nylas-hacktoberfest-2023/code-samples/grant/node/create/index.js:28:16 {
  error: 'internal_error',
  errorCode: 500,
  errorDescription: 'Internal error, contact administrator',
  errorUri: 'https://accounts.nylas.io/#tag/Event-Codes',
  statusCode: 500
}
```

**Comment by relaxedtomato** [comment]
@amit-ksh - will take a look today 👍

**Comment by relaxedtomato** [comment]
@amit-ksh, just confirming two items:

- [ ] 1. Here is the Python SDK version: https://github.com/nylas/nylas-python/tree/v6.0.0-beta
- [ ] 2. Here is some documentation for the Pythong SDK: https://nylas-python-sdk-reference.pages.dev/reference/models/auth/#models.auth.TokenExchangeRequest

are you able to share a code sample or branch that I can take a look at?

**Comment by amit-ksh** [comment]
Code: https://github.com/amit-ksh/nylas-hacktoberfest-2023/tree/create-grants/code-samples/grant/node/create-grants

**Comment by relaxedtomato** [comment]
@amit-ksh - sorry, just realized I confused languages, let me take again.

**Comment by relaxedtomato** [comment]
Here is the Node SDK Reference: https://nylas-nodejs-sdk-reference.pages.dev/

**Comment by amit-ksh** [comment]
hey @relaxedtomato! I'm getting the error on this line `const resp = await nylas.auth.exchangeCodeForToken`. It returned the **500** status when I did some debugging.

I believe this line `const newGrants = await nylas.auth.grants.create` is not causing the issue. 

Also, I tried creating grants using the dashboard it's working as expected as well as this method `nylas.auth.grants.list`.

**Comment by relaxedtomato** [comment]
Okay, let me try this out shortly!

**Comment by amit-ksh** [comment]
I tried to pass all the arguments that I have to `exchangeCodeForToken` method and now it's working I'm not getting ``refreshToken` in response.

```js
const resp = await nylas.auth.exchangeCodeForToken({
      code,
      clientSecret: process.env.CLIENT_SECRET,
      clientId: process.env.CLIENT_ID,
      redirectUri: "http://localhost:3000/oauth/exchange",
    });
```

#### Response of `exchangeCodeForToken` function-

```js
{
  accessToken: 'token',
  grantId: 'id',
  email: 'some@gmail.com',
  expiresIn: 3600,
  idToken: 'token',
  tokenType: 'Bearer',
  scope: 'scope1 scope2'
}
```

Also, when I list grants using this `nylas.auth.grants.list`, I'm getting all the emails I authenticated to but the same is not shown in the **Nylas Dashboard**.

**Comment by relaxedtomato** [comment]
@amit-ksh - this looks good, since I see that you are receiving the `grandId` in return which can be used for subsequent requests.

Let's prepare a PR and I will review 👍

**Comment by relaxedtomato** [comment]
Okay, let me take a look at the PR!
